### ISSUE TITLE
Problem displaying pictures on iOS 11

### ISSUE THREAD

**Issue by AndreasGassmann** [terikon/cordova-plugin-photo-library#105]
I have been using this plugin for a while now, but newer pictures cannot be displayed (at least not the full image). Judging by the time, I think only pictures I took after upgrading to iOS 11 are affected. This leads me to believe that it has something to do with the new image format (HEIC). Does anyone else have this problem and maybe even has a fix?

**Comment by FdezRomero** [comment]
Hi @AndreasGassmann,

I'm having the same problem loading images from the library on an iPhone X, using the native URL methods from your fork (thanks!) and found this issue. I also suspect that the problem comes from HEIC/HEIF/HEVC photos I took with the camera, as the `<img>` throws an `error` event.

I'm currently looking for a way to get HEIF photos transformed to JPG, as it seems there are native methods to do this (or transparently handled by iOS).

I will post any findings here.

**Comment by FdezRomero** [comment]
I failed to notice that the thumbnails using native URL are showing correctly (using `getNativeThumbnailUrl()`), maybe because of the conversion involved. However, the URLs from `getNativePhotoUrl()` don't load.

**Comment by AndreasGassmann** [comment]
Fixed thanks to the PR by @FdezRomero
