### ISSUE TITLE
Get random photo(s)

### ISSUE THREAD

**Issue by henrikhortemo** [terikon/cordova-plugin-photo-library#18]
What is the fastest way of getting one or more random photos from the library?

**Comment by viskin** [comment]
In order to get some photos, you should have their urls or ids. Both are provided by getLibrary function. So you should call getLibrary.
Currently getLibrary returns all the photos on a device. The fastest solution to your problem is to use partialCallback, which will be called each 0.5 sec.
Ideal solution for you needs modifying the library.
You can contribute and implement **limit** option to getLibrary, which will return only given amount of photos. It will work very fast. Do you want?

**Comment by victoria168** [comment]
Hi @viskin , is the 'limit' option available now? Thanks!

**Comment by viskin** [comment]
Sorry still not. Currently have no time.
