### ISSUE TITLE
Issues with resolving image URL.

### ISSUE THREAD

**Issue by hysong15** [terikon/cordova-plugin-photo-library#42]
Love your plugin, and it works pretty well with Ionic.

I am trying to make this work with the Crop plugin (https://github.com/jeduan/cordova-plugin-crop), which takes in an absolute URL of an image.

Is there a way I can resolve the "cdvphotolibrary://" URL into a "file://" URL?

**Comment by viskin** [comment]
@hysong15 Thank you :)
I'm sure that in case of **thumbnails**, you can't resolve "cdvphotolibrary://" files into "file://". The library creates thumbnails on the fly and never creates a file for them.
In case of **full image**, there was file:// access in the past, which I removed because it only worked on Android, and I want this library to be as much cross-platform as possible (to work with iOS also).
Anyway, using cordova-plugin-crop is against the idea of the plugin. The project's aim is to make it possible to use web libraries to work with images on device. So, what we did in our app, we used [cropperjs](https://github.com/fengyuanchen/cropperjs) for image cropping, and it worked very well.

**Comment by viskin** [comment]
Just an afterthought, if you really want to create a file, you can by saving cdvphotolibrary:// to a file:// in your app (directly with JavaScript).
Using [cordova-plugin-file](https://github.com/apache/cordova-plugin-file), this should look like this:
```js
function saveFile (dirEntry, fileData, fileName) {
    dirEntry.getFile(fileName, { create: true, exclusive: false }, function (fileEntry) {
        writeFile(fileEntry, fileData);
    }, onErrorCreateFile);
}

cordova.plugins.photoLibrary.getPhoto(
  libraryItem.id,
  function (fullPhotoBlob) {
    window.resolveLocalFileSystemURL(cordova.file.dataDirectory, function (dirEntry) {
      saveFile(dirEntry, fullPhotoBlob, libraryItem.fileName);
    });
  },
  function (err) {
    console.log('Error occured');
  });
```
