### ISSUE TITLE
order in which the items (photos) are retrieved

### ISSUE THREAD

**Issue by dnmd** [terikon/cordova-plugin-photo-library#68]
Again thanks for this incredible plugin! Keep it up! :)

As we can see on line [Android, L279](https://github.com/terikon/cordova-plugin-photo-library/blob/master/src/android/PhotoLibraryService.java#L279) and [iOS, L49](https://github.com/terikon/cordova-plugin-photo-library/blob/master/src/ios/PhotoLibraryService.swift#L49) is the order in which the items are return ascending. It feels a bit off, if I for instance open Instagram, Imgur, Whatsapp, etc.. I always see the pictures I took most recently first. I don't know if it is intentionally but I can imagine it is more convinient to chance the order. So the user "scrolls back in time"

Of course it is easy to reverse a javascript array, but then we have to "wait" till a function completes to reverse it. What are your thought on this?

**Comment by dnmd** [comment]
I forgot to add a possible solution; for **Android** (`+ " DESC"`) needs to be added;
````java
// ../plugins/cordova-plugin-photo-library/src/android/PhotoLibraryService.java
final String sortOrder = MediaStore.Images.Media.DATE_TAKEN + " DESC";

````
and for **iOS** (`true` becomes `false`)

```` java
// ../plugins/cordova-plugin-photo-library/src/ios/PhotoLibraryService.swift
fetchOptions.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: false)]
````

**Comment by AndreasGassmann** [comment]
I just wanted to post the exact same thing!

I definitely support this change. In my opinion the default should be descending (newest pictures first), ideally you could make it configurable by passing a parameter.

As it is now, the "chunked" feature is useless for anyone who whats to sort their pictures by date (desc) because you have to preload everything and then sort it in js. With this change I (and probably many others) could take advantage of the chunked callbacks.

**Comment by viskin** [comment]
Thank you for the change, published new version
